name: Generate package-lock.json

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install (create lockfile)
        run: npm install

      - name: Commit package-lock.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: add/update package-lock.json"
          file_pattern: "package-lock.json"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"